### ISSUE TITLE
AccordionPane height not adjusting with internal expansion

### ISSUE THREAD

**Issue by kboedges** [mindbody/mbkit#109] opened 2020-08-05 20:08 UTC
The AccordionPane is expanding with a height that is too short for the internal content (some content takes additional time to load in). The only way to get the pane to fully expand, with the correct height, is to open a different pane. This seems to trigger a height recalculation.

## Workaround

My current workaround is setting up a class name to check if the pane is active: 

`className={activePanes.includes(1) ? styles.autoHeight : ''}` 

...and then setting the height of that class to auto:

```
.autoHeight {
    height: auto !important;
}

**Comment by czaas** [comment] 2020-09-25 19:02
Hi Katie, 

Could you help produce an example outside of your existing application? Here's an example of what I'm thinking but don't see the same effect you're describing: https://codesandbox.io/s/distracted-panini-5dqmo?file=/src/App.tsx

**Comment by czaas** [comment] 2021-02-16 16:36
Closing for now due to no reproduction

**Closed by czaas** 2021-02-16 16:36 UTC
